// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ei5g4zJO5MmY6FGqwNbonYxS4sJ9r3U',
    appId: '1:831613341116:web:8aecfd9499abef0e23efb9',
    messagingSenderId: '831613341116',
    projectId: 'shopsmartly-83ba3',
    authDomain: 'shopsmartly-83ba3.firebaseapp.com',
    storageBucket: 'shopsmartly-83ba3.appspot.com',
    measurementId: 'G-0Z6K17QSL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcbmkfRLg7MXxD80bfi7deTX6KkOduXe8',
    appId: '1:831613341116:android:afe745e0b9d923dc23efb9',
    messagingSenderId: '831613341116',
    projectId: 'shopsmartly-83ba3',
    storageBucket: 'shopsmartly-83ba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbkDZoD-lRgKsiUGDW7-_FtKfrhzcV20c',
    appId: '1:831613341116:ios:cfc7e3350c0ab06423efb9',
    messagingSenderId: '831613341116',
    projectId: 'shopsmartly-83ba3',
    storageBucket: 'shopsmartly-83ba3.appspot.com',
    iosClientId: '831613341116-l1spgqqk3sida4pab8b9bfovmn9lf15g.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmartly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbkDZoD-lRgKsiUGDW7-_FtKfrhzcV20c',
    appId: '1:831613341116:ios:d6ea271dfc5865a723efb9',
    messagingSenderId: '831613341116',
    projectId: 'shopsmartly-83ba3',
    storageBucket: 'shopsmartly-83ba3.appspot.com',
    iosClientId: '831613341116-i05eng2rmll2q3sg8ve5qnboqctc0218.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmartly.RunnerTests',
  );
}
